*Note*: I don't think these worked problems make as much sense as a Jupyter Notebook, but I wanted to keep the streak going.

## 1.3A
**Question:** Find the solution *x* for any *b*. From *x* = *A*<sup>-1</sup>*b* read off the inverse matrix *A*<sup>-1</sup>.

In [24]:
# Import necessary libraries
import numpy as np

def printArray(a, title=None):
    # Convenience function to print the array values.
    num_rows, num_cols = a.shape
    if title:
        print(title)
    for i in range(0,num_rows):
        print(a[i][:])
    print('\n')

# Initialize A
A = np.array([[1,0,0],[-1,1,0],[1,-1,1]])
printArray(A, 'A')

# Initialize x (for display)
x = np.array([['x1'],['x2'],['x3']])
printArray(x,'x')

# Initialize Ax (for display)
Ax = np.array([['x1'],['-x1 + x2'], ['x1 - x2 + x3']])
printArray(Ax,'Ax')

# Initialize b (for display)
b = np.array([['b1'],['b2'],['b3']])
printArray(b,'b')

A
[1 0 0]
[-1  1  0]
[ 1 -1  1]


x
['x1']
['x2']
['x3']


Ax
['x1']
['-x1 + x2']
['x1 - x2 + x3']


b
['b1']
['b2']
['b3']




We can solve *Ax* = *b* to see that:  
*x*<sub>1</sub> = *b*<sub>1</sub>  
*x*<sub>2</sub> = *b*<sub>1</sub> + *b*<sub>2</sub>  
*x*<sub>3</sub> = *b*<sub>2</sub> + *b*<sub>3</sub>  
To solve this with numpy we can call linalg.inv() on A.

In [25]:
A_inv = np.linalg.inv(A)
printArray(A_inv, 'A inverse')

A inverse
[1. 0. 0.]
[1. 1. 0.]
[0. 1. 1.]




## 1.3B
**Question:** This *E* is an elimination matrix. *E* has a subtraction and *E<sup>-1</sup>* has an addition.  

In [32]:
# Initialize E
E = np.array([[1,0],['-l', 1]])
printArray(E, 'E')

# Initialize b
b = np.array([['b1'],['b2']])
printArray(b,'b')

# Initialize x
b = np.array([['x1'],['x2']])
printArray(x,'x')

# Initialize Ex
Ex = np.array([['x1',0],['x2', '-l*x1']])
printArray(Ex, 'Ex')

E
['1' '0']
['-l' '1']


b
['b1']
['b2']


x
['x1']
['x2']
['x3']


Ex
['x1' '0']
['x2' '-l*x1']




We can solve *b* = *Ex*  to find that:  
*b<sub>1</sub>* = *x<sub>1</sub>*  
*b<sub>2</sub>* = *x<sub>2</sub>* - *lx<sub>1</sub>*  

To find *E<sup>-1</sup>* we can solve *x* = *E<sup>-1</sup>x* to find that:  
*x<sub>1</sub>* = *b<sub>1</sub>*  
*x<sub>2</sub>* = *lb<sub>1</sub>* + *b<sub>2</sub>*  

In [33]:
# Initialize E_inv
E_inv = np.array([[1,0],['l', 1]])
printArray(E_inv, 'E_inv')

E_inv
['1' '0']
['l' '1']




Like in 1.3A, we can find the inverse of a numpy array with linalg.inv(). Here is an example where *l* = 5.

In [34]:
# Initialize E
E = np.array([[1,0],[5, 1]])
printArray(E, 'E')

# Initialize E_inv
E_inv = np.linalg.inv(E)
printArray(E_inv, 'E_inv')

E
[1 0]
[5 1]


E_inv
[1. 0.]
[-5.  1.]




## 1.3C
**Question:** Change *C* from a cyclic difference to a centered difference producing *x<sub>3</sub>* - *x<sub>1</sub>*:

In [38]:
# Initialize C
C = np.array([[0,1,0],[-1,0,1],[0,-1,0]])
printArray(C, 'C')

# Initialize x
x = np.array([['x1'],['x2'],['x3']])
printArray(x, 'x')

# Initialize b
b = np.array([['b1'],['b2'],['b3']])
printArray(b, 'b')

# Initialize Cx
Cx = np.array([['x2-0'],['x3-x1'],['0-x2']])
printArray(Cx, 'Cx')

C
[0 1 0]
[-1  0  1]
[ 0 -1  0]


x
['x1']
['x2']
['x3']


b
['b1']
['b2']
['b3']


Cx
['x2-0']
['x3-x1']
['0-x2']




*Cx* is a cylic difference because *b<sub>1</sub>* and *b<sub>3</sub>* depend on *x<sub>2</sub>*. This means that it forms a plane in 3D space, rather than filling it entirely. However, if we change *C* to a 4x4 matrix we can make a centered difference.

In [39]:
# Initialize C
C = np.array([[0,1,0,0],[-1,0,1,0],[0,-1,0,1],[0,0,-1,0]])
printArray(C, 'C')

# Initialize x
x = np.array([['x1'],['x2'],['x3'],['x4']])
printArray(x, 'x')

# Initialize b
b = np.array([['b1'],['b2'],['b3'],['b4']])
printArray(b, 'b')

# Initialize Cx
Cx = np.array([['x2-0'],['x3-x1'],['x4-x2'],['0-x3']])
printArray(Cx, 'Cx')

C
[0 1 0 0]
[-1  0  1  0]
[ 0 -1  0  1]
[ 0  0 -1  0]


x
['x1']
['x2']
['x3']
['x4']


b
['b1']
['b2']
['b3']
['b4']


Cx
['x2-0']
['x3-x1']
['x4-x2']
['0-x3']


