## 2.3A
**Question:** What 3 by 3 matrix *E*<sub>21</sub> subtracts 4 times row 1 from row 2? What matrix *P*<sub>32</sub> exchanges row 2 and row 3? If you multiply *A* on the right instead of the left, describe the results *AE*<sub>21</sub> and *AP*<sub>32</sub>.

Strang uses the identity matrix *I* to find these matrices. To subtract 4 times row 1 from row 2, we can set *I*<sub>21</sub> to -4. To exchange rows 2 and 3, we can simply swap their positions in *I*.  
$$E_{21}= \begin{bmatrix} 1 & 0 & 0 \\ -4 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$  
$$P_{32}= \begin{bmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix}$$  

In [83]:
# Import necessary libraries
import numpy as np

def printArray(a, title=None):
    # Convenience function to print the array values.
    num_rows, num_cols = a.shape
    if title:
        print(title)
    for i in range(0,num_rows):
        print(a[i][:])
    print('\n')

# Initialize A
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
printArray(A, 'A')

# Initialize E21
E = np.array([[1,0,0],[-4,1,0],[0,0,1]])
printArray(E, 'E')

# Initialize P32
P = np.array([[1,0,0],[0,0,1],[0,1,0]])
printArray(P, 'P')

A
[1 2 3]
[4 5 6]
[7 8 9]


E
[1 0 0]
[-4  1  0]
[0 0 1]


P
[1 0 0]
[0 0 1]
[0 1 0]




First, let's show the results of *E*<sub>21</sub>*A* and *P*<sub>32</sub>*A*.

In [84]:
EA = np.matmul(E,A)
printArray(EA, 'EA')

PA = np.matmul(P,A)
printArray(PA, 'PA')

EA
[1 2 3]
[ 0 -3 -6]
[7 8 9]


PA
[1 2 3]
[7 8 9]
[4 5 6]




Now, the results of *AE*<sub>21</sub> and *AP*<sub>32</sub>.

In [85]:
AE = np.matmul(A,E)
printArray(AE, 'AE')

AP = np.matmul(A,P)
printArray(AP, 'AP')

AE
[-7  2  3]
[-16   5   6]
[-25   8   9]


AP
[1 3 2]
[4 6 5]
[7 9 8]




As we can see, the commutative property doesn't apply to matrices. Note: this is another example of why I'm glad I turn these into Jupyter notebooks. I had a much harder time trying to write this out and follow along, but the visualization has helped a lot.

## 2.3B
**Question:** Write down the augmented matrix [*A* *b*] with an extra column:
$$\begin{array}{ccc} x +& 2y + 2z = 1 \\ 4x +& 8y + 9z = 3 \\ & 3y + 2z = 1\end{array}$$  
Apply *E*<sub>21</sub> and then *P*<sub>32</sub> to reach a triangular system. Solve by back substituion. What combined matrix *P*<sub>32</sub>*E*<sub>21</sub> will do both steps at once?

In [86]:
# Initialize A
A = np.array([[1,2,2,1],[4,8,9,3],[0,3,2,1]])
printArray(A, 'A')

# Apply E21
EA = np.matmul(E,A)
printArray(EA, 'EA')

# Apply P32
PA = np.matmul(P,EA)
printArray(PA, 'PA')

A
[1 2 2 1]
[4 8 9 3]
[0 3 2 1]


EA
[1 2 2 1]
[ 0  0  1 -1]
[0 3 2 1]


PA
[1 2 2 1]
[0 3 2 1]
[ 0  0  1 -1]




This shows that *z*=-1, *y*=1, and *x*=1. To combine the matrices we can multiply them together: *P*<sub>32</sub>*E*<sub>21</sub> = *U*. We can see that *AU* gives us the identical answer.

In [87]:
U = np.matmul(P,E)

UA = np.matmul(U,A)
printArray(UA, 'UA')

printArray(PA, 'PA')

UA
[1 2 2 1]
[0 3 2 1]
[ 0  0  1 -1]


PA
[1 2 2 1]
[0 3 2 1]
[ 0  0  1 -1]




## 2.3C
**Question:** Multiply these matrices in two ways. First, rows of *A* times columns of *B*. Second, columns of *A* times rows of *B*. That unusual way produces two matrices that add to *AB*. How many separate ordinary multiplcations are needed?

In [88]:
# Initialize A
A = np.array([[3,4],[1,5],[2,0]])
printArray(A, 'A')

# Initialize B
B = np.array([[2,4],[1,1]])
printArray(B, 'B')

AB = np.matmul(A,B)
printArray(AB, 'AB')

A
[3 4]
[1 5]
[2 0]


B
[2 4]
[1 1]


AB
[10 16]
[7 9]
[4 8]




The first way is rows of *A* times columns of *B*. This means we will need to calculate 6 dot products (3 rows * 2 columns), which means we need to do 12 multiplications total (3 * 2 * 2). Each dot product will be one element in the output matrix *C*. The dot product of *A*<sub>1,</sub> and *B*<sub>,1</sub> will be *C*<sub>11</sub>, the dot product of *A*<sub>2,</sub> and *B*<sub>,1</sub> will be *C*<sub>21</sub>, and so on. Note: I'm copying Strang's format instead of using 0 based indexing in my variable names, but I'm still using 0 based indexing to slice, because it's Python.

In [89]:
# Rows of A times columns of B

# first we calculate a dot product for each element of the matrix
c_11 = np.dot(A[0,:],B[:,0])
c_21 = np.dot(A[1,:],B[:,0])
c_31 = np.dot(A[2,:],B[:,0])

c_12 = np.dot(A[0,:],B[:,1])
c_22 = np.dot(A[1,:],B[:,1])
c_32 = np.dot(A[2,:],B[:,1])

# assemble elements into their matrix
C = np.array([[c_11, c_12], [c_21, c_22], [c_31, c_32]])
printArray(C, 'C')

C
[10 16]
[7 9]
[4 8]




The second way is columns of *A* times rows of *B*. This means we just need to do two matrix multiplications and add them together to get the matrix *D*: *A*<sub>,1</sub> * *B*<sub>1,</sub> + *A*<sub>,2</sub> * *B*<sub>2,</sub>.

In [90]:
# Columns of A times rows of B

# Let's extract the columns and rows we need
# and reshape them for matmul
c1 = np.reshape(A[:,0], (3,1))
c2 = np.reshape(A[:,1], (3,1))

r1 = np.reshape(B[0,:], (1,2))
r2 = np.reshape(B[1,:], (1,2))


# get the two matrices
d_1 = np.matmul(c1,r1)
d_2 = np.matmul(c2,r2)
printArray(d_1, 'd1')
printArray(d_2, 'd2')

# add them together
D = d_1 + d_2
printArray(D, 'D')


d1
[ 6 12]
[2 4]
[4 8]


d2
[4 4]
[5 5]
[0 0]


D
[10 16]
[7 9]
[4 8]




Finally, let's prove that all these matrices are the same: *AB* (matrix multiplication of a 3x2 with a 2x2), *C* (rows of *A* times columns of *B*), and *D* (columns of *A* times rows of *B*).

In [91]:
printArray(AB, 'AB')
printArray(C, 'C')
printArray(D, 'D')

AB
[10 16]
[7 9]
[4 8]


C
[10 16]
[7 9]
[4 8]


D
[10 16]
[7 9]
[4 8]


